### ISSUE TITLE
exporters break api

### ISSUE THREAD

**Issue by danielsauceda** [usnistgov/MDCS#17] opened 2016-02-29 04:04 UTC
@shariefyoussef @Guillaume-sousa @dima20899 
situation:
I have script that that gets the ID of a template given its TITLE. confirmed works
in the ADMIN console i change the EXPORTER to JSON and/or CSV
`requests.get("http://xxx.xxx.xxx.xx:8000/rest/templates/select",params={"title":"XXX_Data_model"},auth=("user","password"))` 
returns <Response [404]>

after removing EXPORTERS 

the same code returns Response [200]

NOTE:
fails with 
[{"id":"1234455667abc"}] where this is the template id AND/or the exporter id

**Comment by audip** [comment] 2016-03-30 02:16
I am going to start working on this, but just to clarify my understanding, if we change that to `request.get("/rest/templates/select")`, will making that change across the entire web app fix that bug? Will making that break any other things that I am not aware of?

**Comment by audip** [comment] 2016-03-30 02:18
@danielsauceda: Is that the same as links breaking when you try deploying MDCS in a folder or subfolder of a server?

**Comment by Guillaume-sousa** [comment] 2016-03-30 13:29
Hi @danielsauceda @audip, I could reproduce the bug on my side. It looks like the API is not able to return the template information, when no Exporters are registered for this template. We will start looking into this on our side too, and let you know what's going on.

**Comment by Guillaume-sousa** [comment] 2016-03-31 19:29
We pushed a fix for this issue: https://github.com/usnistgov/MDCS/commit/5824e85f4e2cdb7073aed58ed00d77528d773e60

**Closed by Guillaume-sousa** 2016-03-31 19:29 UTC
Labels: bug
